# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestConsultarCliente():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_consultarCliente(self):
    self.driver.get("http://localhost/Projeto/src/view/I_Inicial.html")
    self.driver.set_window_size(1060, 812)
    self.driver.find_element(By.CSS_SELECTOR, ".center:nth-child(1) > .botao:nth-child(4)").click()
    self.driver.find_element(By.ID, "dados").click()
    dropdown = self.driver.find_element(By.ID, "dados")
    dropdown.find_element(By.XPATH, "//option[. = 'Cpf']").click()
    self.driver.find_element(By.ID, "dados").click()
    self.driver.find_element(By.ID, "d").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(5)").click()
    self.driver.find_element(By.NAME, "bt").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
