# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastrarCliente():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrarCliente(self):
    self.driver.get("http://localhost/Projeto/src/view/I_Inicial.html")
    self.driver.set_window_size(1058, 810)
    self.driver.find_element(By.CSS_SELECTOR, ".center:nth-child(1) > .botao:nth-child(2)").click()
    self.driver.find_element(By.NAME, "cnome").click()
    self.driver.find_element(By.NAME, "cnome").send_keys("JulianoAndrade")
    self.driver.find_element(By.NAME, "cemail").send_keys("juliano@selenium.br")
    self.driver.find_element(By.NAME, "ccpf").send_keys("123.456.788-01")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
    self.driver.find_element(By.NAME, "bt").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
